#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
// Bump version across all three owned package.json files atomically.
// Usage: node scripts/release-version.mjs <new-version>
// Exits non-zero when the argument is not valid semver 2.0.0.
// NOTE: vscode-extension/host/package.json is a build artifact generated by
// vscode-extension/scripts/prepack.mjs at package time; it is NOT an owned
// source manifest and is NOT updated here.
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, renameSync, unlinkSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const semver = require("semver");

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const newVersion = process.argv[2];

if (!newVersion) {
  console.error("Usage: npm run release:version -- <new-version>");
  process.exit(1);
}

const valid = semver.valid(newVersion);
if (!valid) {
  console.error(
    `Invalid semver: "${newVersion}" is not a valid semver 2.0.0 string. No files were modified.`
  );
  process.exit(1);
}

// Owned manifests (vendor/agmsg excluded — third-party tree;
// vscode-extension/host/package.json excluded — build artifact from prepack.mjs).
const manifests = [
  resolve(repoRoot, "package.json"),
  resolve(repoRoot, "electron", "package.json"),
  resolve(repoRoot, "vscode-extension", "package.json"),
];

// Existence check — fail before any write if a manifest is missing.
const missing = manifests.filter((p) => {
  try {
    readFileSync(p);
    return false;
  } catch (err) {
    if (err.code === "ENOENT") return true;
    throw err;
  }
});
if (missing.length > 0) {
  console.error(
    `Cannot bump version: the following manifest(s) are missing:\n` +
      missing.map((p) => `  ${p.replace(repoRoot + "/", "")}`).join("\n") +
      `\nNo files were modified.`
  );
  process.exit(1);
}

// Phase 1 — parse and build all new JSON strings in memory.
// No disk writes yet; if anything fails here no files are touched.
const updates = manifests.map((p) => {
  const data = JSON.parse(readFileSync(p, "utf8"));
  data.version = valid;
  return { final: p, content: JSON.stringify(data, null, 2) + "\n" };
});

// Phase 2 — write each manifest to a sibling temp file, then rename.
// rename(2) is atomic on the same filesystem, so each individual manifest
// transitions from old to new atomically. We write ALL temps before renaming
// ANY target: if a temp-write fails, we clean up temps created so far and
// exit non-zero — no target file is modified.
const pid = process.pid;
const temps = [];
try {
  // Step 2a: write temp files.
  for (const { final, content } of updates) {
    const tmp = `${final}.tmp-${pid}`;
    writeFileSync(tmp, content, "utf8");
    temps.push({ tmp, final });
  }
  // Step 2b: rename each temp to its final location.
  // All temp writes succeeded — proceed with renames.
  for (const { tmp, final } of temps) {
    renameSync(tmp, final);
    console.log(`Updated ${final.replace(repoRoot + "/", "")}`);
  }
} catch (err) {
  // Clean up any temp files that were created before the failure.
  for (const { tmp } of temps) {
    try { unlinkSync(tmp); } catch { /* ignore cleanup errors */ }
  }
  console.error(
    `Version bump failed — no target manifests were modified.\n${err.message}`
  );
  process.exit(1);
}

console.log(`Version bumped to ${valid}`);
